name: myanmarpromotions
description: A new idea.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.0.7
  file_picker: ^4.0.2
  pull_to_refresh: ^2.0.0
  get: ^4.3.8
  google_mobile_ads: ^0.13.0
  dependencies:
  #cupertino_icons: ^1.0.2
  crypto: ^3.0.1
  # cryptography: ^2.0.2
  flutter_image: ^1.0.0
  #cached_network_image: ^3.1.0
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg
